# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-27 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('phone', models.IntegerField()),
                ('company_name', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('on_process', 'On Process'), ('confirmed', 'Confirmed')], default='new', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(choices=[('2017-12-01', '2017-12-01'), ('2017-12-02', '2017-12-02'), ('2017-12-03', '2017-12-03')])),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.CharField(choices=[('nine_nineAndHalf', '9:00 to 9:30'), ('ten_tenAndHalf', '10:00 to 10:30'), ('eleven_elevenAndHalf', '11:00 to 11:30')], max_length=32)),
                ('date_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Date')),
            ],
        ),
    ]
