# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-28 03:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20171127_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date_id',
            field=models.OneToOneField(default=5, on_delete=django.db.models.deletion.PROTECT, to='bookings.Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='time_slot_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='bookings.Time'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='time',
            unique_together=set([('time_slot', 'date_id')]),
        ),
    ]
