# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-28 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20171128_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(default='2017-12-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='time_slot',
            field=models.CharField(default='9:00 to 9:30', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.IntegerField(unique=True),
        ),
        migrations.RemoveField(
            model_name='booking',
            name='date_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='time_slot_id',
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set([('time_slot', 'date')]),
        ),
    ]
