# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-28 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_auto_20171128_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='availability_status',
            field=models.CharField(choices=[('available', 'Available'), ('on_process', 'On Booking Process'), ('booked', 'Booked')], default='available', max_length=55),
            preserve_default=False,
        ),
    ]
