# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-28 06:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_time_availability_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='date_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times', to='bookings.Date'),
        ),
    ]
