# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-28 10:24
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_auto_20171128_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message=b"\n        Phone number must be entered in the format: '+999999999'.\n        Up to 15 digits allowed.\n    ", regex=b'^\\+?1?\\d{9,15}$')]),
        ),
    ]
