# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-04 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_auto_20171214_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='meetup_location',
            field=models.CharField(default='asd', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='company_name',
            field=models.CharField(default='lkjh', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
